apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app: cart-service
    tier: backend
spec:
  replicas: 2
  #strategy:
    #type: RollingUpdate
    #rollingUpdate:
    #  maxUnavailable: 2
    #  maxSurge: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
        tier: backend
    spec:
      containers:
        - name: cart-service
          image: grzekie/node-app:latest
          #ports:
          #  - containerPort: 3000
