apiVersion: v1
kind: Service
metadata:
  name: cart-service-service
  labels:
    app: cart-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
    - port: 3000
      targetPort: 3000